services:
  - type: web
    name: xtractlead
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: GOOGLE_API_KEY
        value: your-google-api-key
